version: "3.9"  # optional since v1.27.0
services:
  database:
    container_name: database
    image: postgres
    ports: 5432:5432
    volumes: 
      - logvolume01:/var/log
    environment:
      POSTGRES_PASSWORD: admin1234
      POSTGRES_USER: database
  redis:
    container_name: redis
    image: redis
    ports: 6379:6379
volumes:
  logvolume01: {}